### ISSUE TITLE
survival tables with tlb_survfit

### ISSUE THREAD

**Issue by DrDataLx** [ddsjoberg/ddsjoberg#1]
Hi!

I was wondering if it is possible to create a table with the tbl_survfit function with this distribution:
col 1: "Overall survival" (name of variable: OS, PFS, EFS, etc)
col 2: survival at 24months for group A (in %)
col 3: survival at 24months for group B (in %)
col 4: p-value

so far I´ve seen the other way (group A and B in the rows and survival at 12-24 months in the columns)

Thank you

Ivan Dlouhy

**Comment by ddsjoberg** [comment]
Dear @DrDataLx , Thank you for your post. The short answer is, no, we're not looking to natively support tables in this format. But you can construct it with somewhat minimal effort. There is an example here: https://github.com/ddsjoberg/gtsummary/issues/1993

**Comment by DrDataLx** [comment]
Thank you for the quick response. 
How could I add a column with p-value for the survival table. I can do for the other variables, but the function does not allow it.

Your package is great! I think it would be very useful the possibility to add the survival comparisson for groups with p-value. If you ever decide to do it please let me know.
Congratulations!
